name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Cordova CLI
        run: npm install -g cordova@11

      - name: Install project dependencies
        run: npm install || echo "No npm dependencies"

      - name: Add Android platform
        run: cordova platform add android@latest

      - name: Build Android Debug APK
        run: cordova build android --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
